### ISSUE TITLE
How to use Bullseye detect C2U edit sites by comparison to genomic sequence without control.matrix.gz file?

### ISSUE THREAD

**Issue by ghost** [mflamand/Bullseye#11]
Hi Mathieu,

In the Bullseye, it mentions "Allows detection of editing site by comparison to genomic sequence or to a control file".

I want to use Bullseye to identify C2U edit sites like HyperTRIBE, without the control.matrix.gz, because I only want to detect edited sites by comparison to genomic sequence.

I run like this, it shows error: Please provide at least an annotation file, an edited matrix and a control matrix or genome file.

```
 perl Find_edit_site.pl --annotationFile annotation.refFlat \
        --EditedMatrix APBOEC1_edit.matrix.gz \
        --editType C2U \
        --minEdit 1 \
        --maxEdit 100 \
        --EditedMinCoverage 10 \
        --MinEditSites 1 \
        --filterBed dbSNP155.bed \
        --outfile APBOEC1_edit.bed \
        --fallback genome.fasta \
        --skip-chr-check
```

How can I use Bullseye to detect C2U edit sites by comparison to genomic sequence without control.matrix.gz?

Many thanks,
Zongmin

**Comment by mflamand** [comment]
Hi Zongmin,

To do this, you should replace `--falback genome.fasta` with `--genome genome.fasta`

Best,

**Comment by ghost** [comment]
Thanks, Mathieu, when using --genome genome.fasta, that works!
